version: 2.1
jobs:

  build_docker:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t proofofwork/pow.co:$CIRCLE_BRANCH . 
      - run:
          name: Push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
            docker push proofofwork/pow.co:$CIRCLE_BRANCH

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - run:
          name: Deploy to Web Servers
          command: |
            mkdir ~/.ssh && touch ~/.ssh/known_hosts
            echo 'pow.co ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOed9xWurUoTT+vTe90SDfnAUfg83GCaO8tcxg04wcH2Z+YQUH8su4OzSdXuNvI5lS1CkJqvyaXehNFa0+eMfpc=' >> ~/.ssh/known_hosts
            ssh root@pow.co "chef-client -o recipe[pow.co::website]"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker
      - deploy:
         requires:
           - build_docker
         filters:
           branches:
             only:
               - master
