version: 2.1
jobs:

  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Dependencies
          command: npm run deploy

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
